# Global bot attributes
bot:
  prefix : '\'
  admins : [368671236370464769]

# Consistent styling
style:
  exception : 0x880808
  light_blue: 0x7DF9FF
  sun_yellow: 0xe1bd27
  bright_green: 0x01fe03
  baby_pink: 0xde5d83

# Links and prompts
props:
  ...

# Directory
directory:
  package : 'bot'
  modules : ['extensions', 'assets', 'utils']
  cogs : ['admin', 'misc', 'utils', 'pictionary']